import Head from 'next/head'
import ButtonBase from '../src/components/general/button/button-base'
import ButtonConfirm from '../src/components/general/button/button-confirm'
import ButtonDanger from '../src/components/general/button/button-danger'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home</h1>
      </main>
    </div>
  )
}
