import Head from 'next/head'
import styles from '../styles/Index.module.scss'

export default function Home() {
  return (
    <div className={styles['page-wrapper']}>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.nav}>
          <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
            <rect width="40" height="40" rx="20" fill="white" />
            <g filter="url(#filter0_d_7_43)">
              <path d="M20 9L30.3923 14.75V26.25L20 32L9.6077 26.25V14.75L20 9Z" fill="#FF0000" fill-opacity="0.46" shape-rendering="crispEdges" />
            </g>
            <defs>
              <filter id="filter0_d_7_43" x="5.60767" y="9" width="28.7847" height="31" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                <feFlood flood-opacity="0" result="BackgroundImageFix" />
                <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
                <feOffset dy="4" />
                <feGaussianBlur stdDeviation="2" />
                <feComposite in2="hardAlpha" operator="out" />
                <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0" />
                <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_7_43" />
                <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_7_43" result="shape" />
              </filter>
            </defs>
          </svg>
          <input type={'search'} placeholder={'Search'}></input>
          <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
            <rect width="40" height="40" rx="20" fill="white" />
            <path d="M35.1992 33C31.531 37.2847 26.0826 40 20 40C13.9174 40 8.46899 37.2847 4.80084 33C8.46899 28.7153 13.9174 26 20 26C26.0826 26 31.531 28.7153 35.1992 33Z" fill="#727272" />
            <path d="M35.1992 33C31.531 37.2847 26.0826 40 20 40C13.9174 40 8.46899 37.2847 4.80084 33C8.46899 28.7153 13.9174 26 20 26C26.0826 26 31.531 28.7153 35.1992 33Z" fill="#727272" />
            <rect x="11" y="7" width="18" height="18" rx="9" fill="#727272" />
            <rect x="11" y="7" width="18" height="18" rx="9" fill="#727272" />
          </svg>
        </nav>
        <section className={styles.content}>
          <section className={styles['post-content']}></section>
          <footer className={styles['footer']}>
            <span>Source:</span>
            <a href='https://github.com/CodeToGive6/Digital-Moment-Team-6' target={'_blank'} rel="noreferrer">Github</a>
          </footer>
        </section>
      </main>
    </div>
  )
}
